server:
  port: 30010

auth:
  clientId: legacy-oauth-client
  secret: secret

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:30000/eureka
  webclient:
    enabled: true

management:
  endpoint:
    web:
      exposure:
        include: refresh, health, info

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
#      default-filters:
#        - name: GlobalAuthFilter
      routes:
        - id: login-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/login
            - Method=POST
          filters:
            - name: LoginFilter
        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=/auth-service/**
            - Method=POST,GET
          filters:
            - RewritePath=/auth-service/(?<segment>.*), /$\{segment}
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=/account-service/**
            - Method=POST,GET,PUT,DELETE
          filters:
            - name : AuthFilter
            - RewritePath=/account-service/(?<segment>.*), /$\{segment}